JS415003: Pls work.

diff --git a/ITE/GCL07/JS415003/Sprawozdanie2/Jenkinsfile b/ITE/GCL07/JS415003/Sprawozdanie2/Jenkinsfile
--- a/ITE/GCL07/JS415003/Sprawozdanie2/Jenkinsfile
+++ b/ITE/GCL07/JS415003/Sprawozdanie2/Jenkinsfile
@@ -111,27 +111,27 @@ EOT
         }
 
         stage('Package') {
-            steps {
-                sh '''
-                    docker rm -f cjson-build-container || true
-                    docker run --name cjson-build-container -d ${CJSON_BUILD} tail -f /dev/null
+    steps {
+        sh '''
+            docker rm -f cjson-build-container || true
+            docker run --name cjson-build-container -d ${CJSON_BUILD} tail -f /dev/null
 
-                    mkdir -p ${PACKAGE_NAME}/lib
-                    mkdir -p ${PACKAGE_NAME}/include
-                    mkdir -p ${PACKAGE_NAME}/docs
+            mkdir -p ${PACKAGE_NAME}/lib
+            mkdir -p ${PACKAGE_NAME}/include
+            mkdir -p ${PACKAGE_NAME}/docs
 
-                    docker cp cjson-build-container:/cjson-build/build/libcjson.so.1.7.18 ${PACKAGE_NAME}/lib/ || echo "libcjson.so.1.7.18 not found"
-                    if [ -f ${PACKAGE_NAME}/lib/libcjson.so.1.7.18 ]; then
-                        (cd ${PACKAGE_NAME}/lib/ && ln -sf libcjson.so.1.7.18 libcjson.so.1 && ln -sf libcjson.so.1 libcjson.so)
-                    fi
+            docker cp cjson-build-container:/cjson-build/build/libcjson.so.1.7.18 ${PACKAGE_NAME}/lib/ || echo "libcjson.so.1.7.18 not found"
+            if [ -f ${PACKAGE_NAME}/lib/libcjson.so.1.7.18 ]; then
+                (cd ${PACKAGE_NAME}/lib/ && ln -sf libcjson.so.1.7.18 libcjson.so.1 && ln -sf libcjson.so.1 libcjson.so)
+            fi
 
-                    docker cp cjson-build-container:/cjson-build/build/libcjson.a ${PACKAGE_NAME}/lib/ || echo "libcjson.a not found"
-                    docker cp cjson-build-container:/cjson-build/cJSON.h ${PACKAGE_NAME}/include/
-                    docker cp cjson-build-container:/cjson-build/README.md ${PACKAGE_NAME}/docs/
-                    docker cp cjson-build-container:/cjson-build/LICENSE ${PACKAGE_NAME}/docs/
-                    docker cp cjson-build-container:/cjson-build/CHANGELOG.md ${PACKAGE_NAME}/docs/ || echo "CHANGELOG.md not found"
+            docker cp cjson-build-container:/cjson-build/build/libcjson.a ${PACKAGE_NAME}/lib/ || echo "libcjson.a not found"
+            docker cp cjson-build-container:/cjson-build/cJSON.h ${PACKAGE_NAME}/include/
+            docker cp cjson-build-container:/cjson-build/README.md ${PACKAGE_NAME}/docs/
+            docker cp cjson-build-container:/cjson-build/LICENSE ${PACKAGE_NAME}/docs/
+            docker cp cjson-build-container:/cjson-build/CHANGELOG.md ${PACKAGE_NAME}/docs/ || echo "CHANGELOG.md not found"
 
-                    cat > ${PACKAGE_NAME}/README.txt << 'EOT'
+            cat > ${PACKAGE_NAME}/README.txt << 'EOT'
 cJSON Library Package ${VERSION}
 ===========================
 
@@ -148,16 +148,17 @@ To use:
 
 Example: gcc -o myapp myapp.c -I./include -L./lib -lcjson
 EOT
-                    sed -i "s/\\\${VERSION}/${VERSION}/g" ${PACKAGE_NAME}/README.txt
+            sed -i "s/\\\${VERSION}/${VERSION}/g" ${PACKAGE_NAME}/README.txt
 
-                    docker stop cjson-build-container
-                    docker rm cjson-build-container
+            docker stop cjson-build-container
+            docker rm cjson-build-container
 
-                    tar -czvf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}/
-                '''
-                archiveArtifacts artifacts: "${PACKAGE_NAME}.tar.gz", fingerprint: true
-            }
-        }
+            tar -czvf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}/
+            mv ${PACKAGE_NAME}.tar.gz ${BASE_DIR}/
+        '''
+    }
+}
+
 
         stage('Publish') {
             steps {
